name: CI

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run:
    name: Compile
    strategy:
      matrix:
        java-version: [17]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: sbt

          # cache sbt dependencies          
      - uses: coursier/cache-action@v6 

      - uses: sbt/setup-sbt@v1

      - name: compile
        run: sbt compile
